//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unconventional_galery.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unconventional_galery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _0_floor {
            get {
                object obj = ResourceManager.GetObject(".0_floor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _1_wall {
            get {
                object obj = ResourceManager.GetObject(".1_wall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _2_dog_tmp {
            get {
                object obj = ResourceManager.GetObject(".2_dog_tmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _3_woj_tmp {
            get {
                object obj = ResourceManager.GetObject(".3_woj_tmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _4_temporaryObject {
            get {
                object obj = ResourceManager.GetObject(".4_temporaryObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _5_pillar {
            get {
                object obj = ResourceManager.GetObject(".5_pillar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _6_displayFilling {
            get {
                object obj = ResourceManager.GetObject(".6_displayFilling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] _7_pipes {
            get {
                object obj = ResourceManager.GetObject(".7_pipes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] fragShader {
            get {
                object obj = ResourceManager.GetObject("fragShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DebugKey is for easier searching in file
        ///GameObjectType is for setting type of object, use -1 when your object represent something else than main types. Every type is having its default texture
        ///WSC is WorldSpaceCords &apos;|&apos; is separator
        ///WSR is WorldSpaceRot &apos;|&apos; is separator
        ///Scale is used for scaling &apos;|&apos; is separator
        ///Override changes the texture of object, override dont have to be present while you dont want to change texture of object from its default. But when using -1 GOT you have to specify override!
        /// [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] vertShader {
            get {
                object obj = ResourceManager.GetObject("vertShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
